baseURL = "https://cadeesalaberry.github.io/"
languageCode = "en-us"
title = "Charles-Antoine de Salaberry"
theme = "coder"

googleAnalytics="G-J9C110825W"

[params]
  author = "Charles-Antoine de Salaberry"
  info = "Full Stack Developer, Tinkerer and Trickster"
  description = "Charles-Antoine de Salaberry's personal website"
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  gravatar = "cadesalaberry@yahoo.com"

  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  footercontent = "French obsessed with digital excellence."
  hideFooter = false
  hideCredits = true
  hideCopyright = true
  since = 2020

  enableTwemoji = true

  # colorsheme = "auto"
  colorsheme = "dark"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/cadesalaberry/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/cadesalaberry/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/cadesalaberry/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "README"
  weight = 2
  url = "readme/"
